--- #YAML:1.0
name:               Crypt-RIPEMD160
version:            0.05
abstract:           Perl extension for the RIPEMD-160 Hash function
author:
    - Christian H. Geuer-Pollmann
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    Test::More:  0
resources:
    homepage:    http://wiki.github.com/toddr/Crypt-RIPEMD160
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/toddr/Crypt-RIPEMD160/tree/master
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
